apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-web-server-ingress-2
  annotations:
    kubernetes.io/ingress.class: gce
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: gce
  rules:
  - http:
      paths:
      - path: /nginx/(.*)
        pathType: Prefix
        backend:
          service:
            name: my-nginx-server-svc
            port:
              number: 8082