apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-rewrite-config
spec:
  cdn:
    enabled: false
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-web-server-ingress-2
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.kubernetes.io/default-backend-config: '{"default":"nginx-rewrite-config"}'
spec:
  ingressClassName: gce
  defaultBackend:
    service:
      name: my-nginx-server-svc
      port:
        number: 8082
  rules:
  - http:
      paths:
      - path: /nginx/
        pathType: Prefix
        backend:
          service:
            name: my-nginx-server-svc
            port:
              number: 8082