-- =============================================================
-- ORACLE TEST SCHEMA SETUP
-- =============================================================

-- -------------------------------------------------------------
-- 1. CREATE TEST SCHEMA (TABLESPACE)
-- -------------------------------------------------------------
CREATE TABLESPACE TEST_TS
    DATAFILE 'TEST_TS.DBF'
    SIZE 50M
    AUTOEXTEND ON
    NEXT 10M
    MAXSIZE 200M;


-- -------------------------------------------------------------
-- 2. CREATE USER FOR TEST SCHEMA
-- -------------------------------------------------------------
CREATE USER TEST_USER
    IDENTIFIED BY "TestPass#2024"
    DEFAULT TABLESPACE TEST_TS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON TEST_TS;

-- GRANT BASIC SESSION AND OBJECT CREATION PRIVILEGES
GRANT CREATE SESSION    TO TEST_USER;
GRANT CREATE TABLE      TO TEST_USER;
GRANT CREATE VIEW       TO TEST_USER;
GRANT CREATE SEQUENCE   TO TEST_USER;


-- -------------------------------------------------------------
-- 3. CREATE 3 DUMMY TABLES (OWNED BY TEST_USER)
-- -------------------------------------------------------------

-- NOTE: RUN AS DBA OR USE SCHEMA PREFIX AS SHOWN BELOW

CREATE TABLE TEST_USER.EMPLOYEES (
    EMPLOYEE_ID   NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME    VARCHAR2(50)  NOT NULL,
    LAST_NAME     VARCHAR2(50)  NOT NULL,
    EMAIL         VARCHAR2(100) UNIQUE NOT NULL,
    HIRE_DATE     DATE          DEFAULT SYSDATE NOT NULL,
    SALARY        NUMBER(10, 2),
    IS_ACTIVE     CHAR(1)       DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE TABLE TEST_USER.DEPARTMENTS (
    DEPARTMENT_ID   NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100) NOT NULL,
    LOCATION        VARCHAR2(200),
    MANAGER_ID      NUMBER(10),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE TABLE TEST_USER.PROJECTS (
    PROJECT_ID    NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_NAME  VARCHAR2(150) NOT NULL,
    DEPARTMENT_ID NUMBER(10)    REFERENCES TEST_USER.DEPARTMENTS(DEPARTMENT_ID),
    START_DATE    DATE,
    END_DATE      DATE,
    BUDGET        NUMBER(15, 2),
    STATUS        VARCHAR2(20)  DEFAULT 'PLANNED'
                                CHECK (STATUS IN ('PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED')),
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);


-- -------------------------------------------------------------
-- 4. GRANT PRIVILEGES ON DUMMY TABLES TO TEST_USER
--    (RUN AS DBA / TABLE OWNER IF NEEDED)
-- -------------------------------------------------------------

-- FULL DML ACCESS ON ALL THREE TABLES
GRANT SELECT, INSERT, UPDATE, DELETE ON TEST_USER.EMPLOYEES   TO TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEST_USER.DEPARTMENTS TO TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEST_USER.PROJECTS    TO TEST_USER;

-- ALLOW TEST_USER TO GRANT SELECT PRIVILEGES FURTHER (OPTIONAL)
GRANT SELECT ON TEST_USER.EMPLOYEES   TO TEST_USER WITH GRANT OPTION;
GRANT SELECT ON TEST_USER.DEPARTMENTS TO TEST_USER WITH GRANT OPTION;
GRANT SELECT ON TEST_USER.PROJECTS    TO TEST_USER WITH GRANT OPTION;
